"""capasity -> capacity

Revision ID: 00f529a6a785
Revises: 0af47dd7e3c2
Create Date: 2022-05-21 09:53:42.602201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f529a6a785'
down_revision = '0af47dd7e3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('capacity', sa.String(), nullable=False))
    op.drop_column('articles', 'capasity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('capasity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'capacity')
    # ### end Alembic commands ###
