"""'Array'

Revision ID: bd08c841f688
Revises: 738e6e5c8de3
Create Date: 2022-05-18 20:40:59.363961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd08c841f688'
down_revision = '738e6e5c8de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'articles', ['source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'source')
    # ### end Alembic commands ###
